"""Integration checks against real fixture Parquets generated by climasus4r."""

from __future__ import annotations

import json
from pathlib import Path

import duckdb
import pandas as pd
import pytest

import climasus4py as cs
import climasus4py.utils.data as data_utils

ROOT = Path(__file__).resolve().parents[2]
FIXTURES = ROOT / "fixture_reais"
HEALTH = FIXTURES / "health" / "sih_rd_ac_2023_01.parquet"
CLIMATE = FIXTURES / "climate" / "inmet_sp_a701_2023.parquet"


pytestmark = pytest.mark.skipif(
    not HEALTH.is_file() or not CLIMATE.is_file(),
    reason="fixture_reais Parquets are not available",
)


@pytest.fixture
def isolated_climasus_data(tmp_path: Path, monkeypatch: pytest.MonkeyPatch):
    data_root = tmp_path / "climasus-data"
    data_root.mkdir()
    (data_root / "manifest.json").write_text(json.dumps({"version": "test"}))
    monkeypatch.setenv("CLIMASUS_DATA_DIR", str(data_root))
    data_utils._DATA_DIR = None
    data_utils.load_json.cache_clear()
    try:
        yield data_root
    finally:
        data_utils._DATA_DIR = None
        data_utils.load_json.cache_clear()


def test_real_health_fixture_aggregates_lazily():
    rel = cs.sus_read(HEALTH)
    canonical = cs.sus_sql(
        rel,
        """
        SELECT
            CAST(TRY_STRPTIME(CAST(DT_INTER AS VARCHAR), '%Y%m%d') AS DATE) AS date,
            CAST(MUNIC_RES AS VARCHAR) AS municipality_code,
            VAL_TOT AS value
        FROM {data}
        WHERE DT_INTER IS NOT NULL
        """,
    )

    with pytest.warns(UserWarning, match="sus_data_aggregate"):
        aggregated = cs.sus_data_aggregate(canonical, time="month", geo="municipality")
    df = cs.materialize(aggregated, quiet=True)

    assert int(df["count"].sum()) == 4165
    assert "sum_value" in df.columns
    assert df["sum_value"].sum() > 0


def test_real_climate_fixture_enriches_with_idw(
    isolated_climasus_data: Path,
):
    climate_dir = isolated_climasus_data / "assets" / "climate"
    climate_dir.mkdir(parents=True)
    observations = climate_dir / "inmet_observations_2023.parquet"
    weights = climate_dir / "idw_weights_municipality.parquet"
    conn = duckdb.connect()
    conn.sql(
        f"""
        COPY (
            SELECT
                station_code AS station_id,
                CAST(date AS DATE) AS date,
                CAST(tair_dry_bulb_c AS DOUBLE) AS temp_mean,
                CAST(rainfall_mm AS DOUBLE) AS precipitation
            FROM read_parquet('{CLIMATE.as_posix()}')
            WHERE station_code = 'A701'
        ) TO '{observations.as_posix()}' (FORMAT PARQUET)
        """
    )
    pd.DataFrame(
        {"municipality_code": ["3550308"], "station_id": ["A701"], "weight": [1.0]}
    ).to_parquet(weights, index=False)

    rel = cs.sus_sql(
        cs.sus_read(CLIMATE),
        """
        SELECT
            ROW_NUMBER() OVER () AS row_id,
            '3550308' AS municipality_code,
            CAST(date AS DATE) AS date
        FROM {data}
        WHERE station_code = 'A701'
        ORDER BY date
        LIMIT 10
        """,
    )

    with pytest.warns(UserWarning, match="sus_climate"):
        enriched = cs.sus_climate(
            rel,
            variables=["temp_mean", "precipitation"],
            years=[2023],
        )
    df = cs.materialize(enriched, how="pandas", quiet=True)

    assert len(df) == 10
    assert df["temp_mean"].notna().all()
    assert df["precipitation"].notna().all()


def test_installed_spatial_assets_join_real_municipality():
    rel = cs.sus_sql(
        cs.sus_read(HEALTH),
        """
        SELECT '3550308' AS municipality_code
        FROM {data}
        LIMIT 1
        """,
    )

    with pytest.warns(UserWarning, match="sus_spatial"):
        enriched = cs.sus_spatial(rel, geo_level="municipality")
    df = cs.materialize(enriched, how="pandas", quiet=True)

    assert "Paulo" in df.loc[0, "spatial_name"]
    assert isinstance(df.loc[0, "geometry_wkt"], str)
    assert df.loc[0, "geometry_wkt"]


def test_installed_census_assets_join_real_municipality():
    rel = cs.sus_sql(
        cs.sus_read(HEALTH),
        """
        SELECT '3550308' AS municipality_code
        FROM {data}
        LIMIT 1
        """,
    )

    with pytest.warns(UserWarning, match="sus_census"):
        enriched = cs.sus_census(
            rel,
            year=2022,
            variables=["population_2021", "population_2025"],
        )
    df = cs.materialize(enriched, quiet=True)

    assert int(df.loc[0, "population_2021"]) > 0
    assert int(df.loc[0, "population_2025"]) > 0
